name: Checks
on: [push]

jobs:
  check-format:
    name: Check format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Format check
        run: bun run check:fmt
  check-lint:
    name: Check lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Typegen
        run: bun run typegen
      - name: Build apps and packages
        run: bun run build
      - name: Lint check
        run: bun run check:lint
